//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDoctor
    {
        public int DoctorId { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public int DoctorJMBG { get; set; }
        public int BankAccount { get; set; }
        public string Username { get; set; }
        public string DoctorPassword { get; set; }
    }
}
