//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDoctor
    {
        public int DoctorId { get; set; }
        public string FullName { get; set; }
        public string DoctorJMBG { get; set; }
        public string BankAccount { get; set; }
        public string Username { get; set; }
        public string DoctorPassword { get; set; }
    }
}
